    <footer>
        <div class="footer_section">
            <h2> About Ranger's Watch </h2>
            <p> Ranger's Watch was developed by Kenneth Mak as a final project for course 4WW3 during Fall 2021, at McMaster University. <br> 
                It tracks and updates archery centres  around your location, providing the overall ratings, 
                description, and location of a centre. Users are able to submit new or unlisted centres to the database. </p>
        </div>
    </footer>