    <footer>
        <div class="footer_section">
            <h2> About Ranger's Watch </h2>
            <p> Ranger's Watch was developed by Kenneth Mak as a final project for course 4WW3 during Fall 2021, at McMaster University. <br> 
                It tracks and updates archery centres  around your location, providing the overall ratings, 
                description, and location of a centre. Users are able to submit new or unlisted centres to the database. </p>
                
            <br>
            <p> Picture from: <a href="https://media.istockphoto.com/photos/silhouette-archery-shoots-a-bow-at-the-target-picture-id497894913?k=20&m=497894913&s=170667a&w=0&h=TVTOGKKyaXymuQT2G8Hk8NTfqbFH14eIWOfu_6-NGUI=">iStockPhoto</a> </p>	
   
        </div>
    </footer>
    