    <header>
        <div class="header_title"> 
            <h1>Ranger's Watch</h1>
        </div>

        <div class="nav_menu">
            <!-- return to home page -->
            <a href="main.php">
                <div class="nav_button">
                    <i class="material-icons">home</i>
                    <p class="nav_button_text">Home</p>
                </div>
            </a>
            <!-- return to search page -->
            <a href="search.php">
                <div class="nav_button">
                    <i class="material-icons">search</i>
                    <p class="nav_button_text">Search</p>
                </div>
            </a>
            <!-- submit new location -->
            <a href="submission.php">
                <div class="nav_button">
                    <i class="material-icons">add</i>
                    <p class="nav_button_text">Submit</p>
                </div>
            </a>
            <!-- account login -->
            <a href="signin.php">
                <div class="nav_button">
                    <i class="material-icons">login</i>
                    <p class="nav_button_text">Sign In</p>
                </div>
            </a>
            <!-- account registration -->
            <a href="registration.php">
                <div class="nav_button">
                    <i class="material-icons">person_add</i>
                    <p class="nav_button_text">Sign Up</p>
                </div>
            </a>
        </div>
    </header>